services:
  api:
    container_name: apollo-federation
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      PORT: 4000
    command: npm run start:dev
    ports:
      - 4000:4000
