federation_version: 2
subgraphs:
  distribution:
    routing_url: http://localhost:3000/graphql
    schema:
      subgraph_url: http://localhost:3000/graphql
  content:
    routing_url: http://localhost:3003/graphql
    schema:
      subgraph_url: http://localhost:3003/graphql
  notification:
    routing_url: http://localhost:3002/graphql
    schema:
      subgraph_url: http://localhost:3002/graphql